development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: tamashii-checkin_development
  # adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: tamashii-checkin_production
